export const MESSAGE_TYPES = {
    ELEMENT_ACTION: 'ELEMENT_ACTION',
    GET_VIDEOS_DATA: 'GET_VIDEOS_DATA',
    CHECK_ELEMENT_VIDEO_SELECTED: "CHECK_ELEMENT_VIDEO_SELECTED",
    RESULT_CHECK_ELEMENT_VIDEO_SELECTED: 'RESULT_CHECK_ELEMENT_VIDEO_SELECTED',
    ADD_EVENTS_ELEMENT: 'ADD_EVENTS_ELEMENT',
    REMOVE_EVENTS_ELEMENTS: 'REMOVE_EVENTS_ELEMENTS',
    CHECK_CONNECTION: 'CHECK_CONNECTION'
}